### ISSUE TITLE
Failing in dependency

### ISSUE THREAD

**Issue by sammyraul** [cqerl/cqerl#160]
I am not able to build cqerl, it crashes with issue in "snappy"

My OTP verion is 19.

make[1]: Entering directory `/home/shobhit/twine/car/multiscreen-server/twine2.0/erl/tls/deps/cqerl'
 DEP    snappy
{"init terminating in do_boot",{{badmatch,{ok,{{"HTTP/1.1",403,"Forbidden"},[{"date","Fri, 23 Aug 2019 03:18:35 GMT"},{"server","AmazonS3"},{"content-length","243"},{"content-type","application/xml"},{"x-amz-request-id","47CE5E3423D60A40"},{"x-amz-id-2","5CC5k3bO6/UQXohH2/vBjyhVgfQ2XSRk/GakIJ6dl+6+CNqR/HFii61m40WEarOx5+HhtVg3Jzc="}],<<60,63,120,109,108,32,118,101,114,115,105,111,110,61,34,49,46,48,34,32,101,110,99,111,100,105,110,103,61,34,85,84,70,45,56,34,63,62,10,60,69,114,114,111,114,62,60,67,111,100,101,62,65,99,99,101,115,115,68,101,110,105,101,100,60,47,67,111,100,101,62,60,77,101,115,115,97,103,101,62,65,99,99,101,115,115,32,68,101,110,105,101,100,60,47,77,101,115,115,97,103,101,62,60,82,101,113,117,101,115,116,73,100,62,52,55,67,69,53,69,51,52,50,51,68,54,48,65,52,48,60,47,82,101,113,117,101,115,116,73,100,62,60,72,111,115,116,73,100,62,53,67,67,53,107,51,98,79,54,47,85,81,88,111,104,72,50,47,118,66,106,121,104,86,103,102,81,50,88,83,82,107,47,71,97,107,73,74,54,100,108,43,54,43,67,78,113,82,47,72,70,105,105,54,49,109,52,48,87,69,97,114,79,120,53,43,72,104,116,86,103,51,74,122,99,61,60,47,72,111,115,116,73,100,62,60,47,69,114,114,111,114,62>>}}},[{erl_eval,expr,3,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

Any help would be highly appreciated.

**Comment by matehat** [comment]
Should be fixed now that we replaced with snappyer
