### ISSUE TITLE
integrity_SUITE's async_insertion_roundtrip seems to depend on the Cassandra partitioner

### ISSUE THREAD

**Issue by portasynthinca3** [cqerl/cqerl#165]
`async_insertion_roundtrip` does this, per my understanding:
- assumes there's already a row in `test_keyspace_2.entries1`:
  ```
   id      | age | email
  ---------+-----+---------------------
     hello |  18 | mathieu@damours.org
  ```
- inserts a new one:
  ```
   id      | age | email
  ---------+-----+---------------------
   1234123 |  45 |    yvon@damours.org
  ```
- fetches all rows from `test_keyspace_2.entries1`
- gets the second one using `cqerl:next/1`
- matches it against the `1234123`/`45`/`yvon@damours.org` triplet, the exact data this function has inserted in step 2

The problem is that the order of these rows depends on the partitioner the cluster has been configured with. I'm using `ByteOrderedPartitioner`, which isn't ideal, I know, but it seems to be causing a problem with this unit test

**Comment by matehat** [comment]
Ah, interesting. It's true that the tests shouldn't depend on the partitioner being used. Can you make the test more resilient?

**Comment by portasynthinca3** [comment]
Okay, I'll take a look
