### ISSUE TITLE
Please, publish the latest version of CQErl to Hex.pm 🥺

### ISSUE THREAD

**Issue by vassilevsky** [cqerl/cqerl#174]
Hello 🙃

I maintain an application which has both **Brod** and **CQEx** as dependencies. They both have **SnappyEr** as a dependency. And that is the problem.

The latest **Brod 3.16** depends on **snappyer 1.2.8**.

The previous **Brod 3.15** depends on **snappyer 1.2.5** (via **kafka_protocol**).

The latest **CQErl** (on Hex.pm) depends on **snappyer 1.2.6** and that does not match any of the versions that Brod uses 😩 Mix simply cannot resolve all dependencies 😭

I noticed that the latest **CQErl** in this repository already uses **snappyer 1.2.8**. It matches the Brod one! But it's not on Hex.pm yet 😕

Please, release the latest code to Hex.pm 🥺

**Comment by matehat** [comment]
Sorry for the late reply, it's now published!
